---
name: DeadStarAC
author: Smile2Cheat
version: 1.1.0
main: Smile2Cheat\deadstar\Main
api: 4.0.0
src-namespace-prefix: Smile2Cheat\deadstar

commands:
  alerts:
    description: Enable / Disable the anticheat alerts
    permission: deadstar.alerts

permissions:
  deadstar.alerts:
    default: op
    description: Enable / Disable alerts the anticheat
...
